import { useEffect, useState } from 'react'
import data from '../content/site-content.json'
import './App.css'

const route = () => window.location.hash.slice(2) || 'home'
const profiles = data.profiles || []
const gallery = data.gallery || []
const entries = data.entries || []
const heroImages = data.site.heroImages?.length ? data.site.heroImages : data.site.heroImage ? [data.site.heroImage] : []
const publicUrl = (url) => url?.startsWith('/') ? `${import.meta.env.BASE_URL}${url.slice(1)}` : url

function Header() { const headerLines = data.site.titleLines?.filter(Boolean) || [data.site.title]; return <header className="site-header"><a className="wordmark" href="#/">{headerLines.map((line, index) => <span key={index}>{line}{index < headerLines.length - 1 && <br/>}</span>)}</a><nav><a href="#/">메인</a><a href="#/profiles">캐릭터</a><a href="#/gallery">갤러리</a><a href="#/archive">도감</a></nav></header> }
function Back({ to = '#/' }) { return <a className="back-link" href={to}>← 돌아가기</a> }
function Empty({ children }) { return <div className="empty-page">{children}</div> }

function Home() { const [active, setActive] = useState(entries[0]); const [heroImage] = useState(() => heroImages[Math.floor(Math.random() * heroImages.length)]); const titleLines = data.site.titleLines?.filter(Boolean) || [data.site.title]; return <main><section className="hero-section"><div className="hero-copy-block"><p className="eyebrow">{data.site.heroEyebrow}</p><h1>{titleLines.map((line, index) => <span key={index}>{line}{index < titleLines.length - 1 && <br />}</span>)}</h1><p className="hero-copy">{data.site.heroLines.map(x => <span key={x}>{x}<br /></span>)}</p><a className="primary-link" href="#/archive">기록 살펴보기 →</a></div>{heroImage ? <div className="hero-image"><img src={publicUrl(heroImage)} alt="메인 대표 이미지"/></div> : <div className="image-placeholder"><span>HERO IMAGE</span><span>수정툴에서 대표 이미지를 추가할 수 있습니다.</span></div>}</section><section className="section"><div className="section-heading"><p className="eyebrow">CHARACTERS</p><h2>캐릭터 프로필</h2></div><a className="profile-card preview-link" href="#/profiles"><p className="file-number">FILES</p><div><h3>{profiles.length ? `${profiles.length}명의 인물 기록` : '기록될 인물'}</h3><p>캐릭터의 이미지와 상세 프로필을 확인할 수 있습니다.</p></div><span>전체 보기 →</span></a></section><section className="section"><div className="section-heading"><p className="eyebrow">VISUAL RECORDS</p><h2>갤러리</h2></div><a className="gallery-grid preview-link" href="#/gallery">{gallery.slice(0, 3).map((x,i)=><figure className="gallery-image" key={x.url}><img src={publicUrl(x.url)} alt={x.title}/><figcaption>{x.title}</figcaption></figure>)}</a></section>{entries.length > 0 && <section className="section archive-section"><div className="archive-layout"><div className="entry-list">{entries.map(entry => <button className={entry.id === active.id ? 'entry active' : 'entry'} key={entry.id} onClick={() => setActive(entry)}><span>{entry.type}</span>{entry.title}<b>→</b></button>)}</div><article className="entry-preview"><p className="eyebrow">{active.type}</p><h3>{active.title}</h3><p>{active.text}</p><a className="inline-link" href="#/archive">도감 전체 보기 →</a></article></div></section>}</main> }

function Profiles() { if (!profiles.length) return <main className="subpage"><Back to="#/"/><p className="eyebrow">CHARACTER FILES</p><h1>캐릭터 프로필</h1><Empty><h2>첫 번째 인물을 기다리고 있습니다.</h2><p>수정툴에서 캐릭터를 추가해 주세요.</p></Empty></main>; return <main className="subpage"><Back/><p className="eyebrow">CHARACTER FILES</p><h1>캐릭터 프로필</h1><div className="pinterest-grid">{profiles.map((p,i)=><a className="pin-card" href={`#/profiles/${i}`} key={p.id}><img src={publicUrl(p.image) || '/placeholder.svg'} alt={p.name}/><span>{p.name}</span><small>{p.summary}</small></a>)}</div></main> }
function ProfileDetail({ index }) { const p=profiles[index]; if(!p) return <Profiles/>; return <main className="subpage"><Back to="#/profiles"/><div className="gallery-viewer"><div className="gallery-large">{p.image?<img src={publicUrl(p.image)} alt={p.name}/>:<div className="gallery-placeholder">NO IMAGE</div>}</div><article className="gallery-story"><p className="eyebrow">CHARACTER FILE</p><h1>{p.name}</h1><p className="profile-summary">{p.summary}</p><p>{p.story}</p>{p.logoImage && <img className="profile-logo-image" src={publicUrl(p.logoImage)} alt={`${p.name} 로고`}/>}</article></div></main> }
function Gallery() { if(!gallery.length)return <main className="subpage"><Back/><p className="eyebrow">VISUAL RECORDS</p><h1>갤러리</h1><Empty><h2>아직 이미지가 없습니다.</h2></Empty></main>;return <main className="subpage"><Back/><p className="eyebrow">VISUAL RECORDS</p><h1>갤러리</h1><div className="pinterest-grid">{gallery.map((g,i)=><a className="pin-card" href={`#/gallery/${i}`} key={g.url}><img src={publicUrl(g.url)} alt={g.title}/><span>{g.title}</span></a>)}</div></main> }
function GalleryDetail({ index }) { const g=gallery[index];if(!g)return <Gallery/>;return <main className="subpage"><Back to="#/gallery"/><div className="gallery-viewer"><div className="gallery-large"><img src={publicUrl(g.url)} alt={g.title}/></div><article className="gallery-story"><p className="eyebrow">ILLUSTRATION</p><h1>{g.title}</h1><p>{g.story}</p></article></div></main> }
function Archive() {
  const folders = entries.reduce((result, entry) => { const folder = entry.type || '기타'; (result[folder] ||= []).push(entry); return result }, {})
  const folderNames = Object.keys(folders)
  const [folder, setFolder] = useState(folderNames[0])
  const [entry, setEntry] = useState(entries[0])
  if (!entries.length) return null
  const selectFolder = (name) => { setFolder(current => current === name ? null : name); if (folder !== name) setEntry(folders[name][0]) }
  const selectEntry = (next) => { setEntry(next); setFolder(next.type || '기타') }
  return <main className="subpage"><Back/><p className="eyebrow">CONNECTED ENCYCLOPEDIA</p><h1>세계관 도감</h1><div className="archive-layout folder-layout"><div className="entry-list">{folderNames.map(name => <div className="folder" key={name}><button className={folder === name ? 'folder-button active' : 'folder-button'} onClick={() => selectFolder(name)}><b className={folder === name ? 'folder-chevron open' : 'folder-chevron'}>›</b>{name}<span>{folders[name].length}</span></button>{folder === name && folders[name].map(e => <button className={e.id === entry.id ? 'entry active' : 'entry'} onClick={() => selectEntry(e)} key={e.id}>{e.title}<b>→</b></button>)}</div>)}</div><article className="entry-preview"><p className="eyebrow">{entry.type}</p><h2>{entry.title}</h2><p>{entry.text}</p><div className="related">연결 문서 {(entry.links||[]).map(link=><button key={link} onClick={()=>{const found=entries.find(e=>e.title===link);if(found)selectEntry(found)}}>{link}</button>)}</div></article></div></main>
}
function App(){const [r,setR]=useState(route);useEffect(()=>{const f=()=>{setR(route());scrollTo(0,0)};addEventListener('hashchange',f);return()=>removeEventListener('hashchange',f)},[]);let page=r==='profiles'?<Profiles/>:r.startsWith('profiles/')?<ProfileDetail index={Number(r.split('/')[1])}/>:r==='gallery'?<Gallery/>:r.startsWith('gallery/')?<GalleryDetail index={Number(r.split('/')[1])}/>:r==='archive'?<Archive/>:<Home/>;return <div className="site-shell"><Header/><div className="page-transition" key={r}>{page}</div><footer><span>{data.site.title}</span><a href={data.site.ownerLink}>{data.site.ownerName} ↗</a></footer></div>}
export default App
